spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:multitenant_db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        tenant_identifier_resolver: com.example.multitenant.config.TenantIdentifierResolver

  cache:
    type: simple

  flyway:
    enabled: false

management:
  health:
    redis:
      enabled: false
