-- Add created_by and updated_by columns for audit tracking
ALTER TABLE products ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE products ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
ALTER TABLE webhook_endpoints ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE webhook_endpoints ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
